const D=window.HEB_DATA;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(b=>b.classList.remove('active'));$(`#${name}View`).classList.add('active');const nav=$(`.nav-item[data-view="${name}"]`);if(nav)nav.classList.add('active');const titles={overview:'H-E-B Network Overview',stores:'Store & Delivery Execution',items:'Item Tracker',sales:'Added Sales',schedule:'Delivery Schedule'};$('#pageTitle').textContent=titles[name];$('#sidebar').classList.remove('open')}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
function deliveryCount(day){return D.deliverySummary[day]||0}
function marketBreakdown(day){const out={};D.stores.filter(s=>s.deliveryDays.includes(day)).forEach(s=>out[s.market]=(out[s.market]||0)+1);return Object.entries(out).sort((a,b)=>b[1]-a[1])}
function renderOverview(){const today=dayNames[now.getDay()];const markets=Object.keys(D.markets).length;$('#heroInstock').textContent=D.stores.length.toLocaleString();$('#kpiInstock').textContent=D.stores.length.toLocaleString();$('#kpiGap').textContent='real store master';$('#kpiGreen').textContent=deliveryCount(today)||'—';$('#greenPct').textContent=today==='Sat'||today==='Sun'?'No weekday route':today+' deliveries';$('#kpiCases').textContent=markets;$('#caseTrend').textContent='Texas markets';$('#kpiDollars').textContent=D.stores.length;$('#dollarTrend').textContent='coordinates loaded';$('#sidebarGap').textContent='Store master loaded';$('#sidebarProgress').style.width='100%';
 const preview=D.stores.slice(0,5);$('#overviewStoreRows').innerHTML=preview.map(s=>`<tr><td><strong>${s.name}</strong><br><span style="color:#8b93a1">${s.address}</span></td><td>${s.city}</td><td><strong>${s.market}</strong></td><td>${s.deliveryDays.join(', ')||'—'}</td><td><span class="pill green">LOADED</span></td></tr>`).join('');
 $('#priorityList').innerHTML=Object.entries(D.markets).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([m,c])=>`<div class="priority-item"><span class="priority-dot"></span><div class="priority-main"><strong>${m}</strong><span>H-E-B store network</span></div><div class="priority-score">${c} stores</div></div>`).join('');
 $('#dowBars').innerHTML=Object.entries(D.deliverySummary).map(([day,v])=>`<div class="bar-row"><strong>${day}</strong><div class="bar-track"><div class="bar-fill" style="width:${v/148*100}%"></div></div><strong>${v}</strong></div>`).join('');drawBarChart($('#trendChart'),Object.values(D.deliverySummary),Object.keys(D.deliverySummary))}
function fillFilters(){[...new Set(D.stores.map(s=>s.city))].sort().forEach(c=>$('#cityFilter').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));Object.keys(D.markets).sort().forEach(m=>$('#marketFilter').insertAdjacentHTML('beforeend',`<option value="${m}">${m}</option>`));['Mon','Tue','Wed','Thu','Fri'].forEach(d=>$('#deliveryFilter').insertAdjacentHTML('beforeend',`<option value="${d}">${d}</option>`))}
function renderStores(){const market=$('#marketFilter').value,city=$('#cityFilter').value,day=$('#deliveryFilter').value,q=$('#globalSearch').value.toLowerCase();const arr=D.stores.filter(s=>(market==='all'||s.market===market)&&(city==='all'||s.city===city)&&(day==='all'||s.deliveryDays.includes(day))&&(!q||`${s.name} ${s.city} ${s.market} ${s.address} ${s.id}`.toLowerCase().includes(q)));$('#storeRows').innerHTML=arr.map(s=>`<tr><td><strong>${s.name}</strong><br><span style="color:#8b93a1">#${s.id}</span></td><td>${s.city}</td><td>${s.market}</td><td>${s.address}</td><td><strong>${s.deliveryDays.join(', ')||'—'}</strong></td><td>${s.deliveryDays.length}</td><td>${s.latitude.toFixed(4)}, ${s.longitude.toFixed(4)}</td><td><button class="text-btn" onclick="copyStore('${s.id}')">Copy →</button></td></tr>`).join('')||'<tr><td colspan="8">No stores match the current filters.</td></tr>';$('#storeCount').textContent=`${arr.length} of ${D.stores.length} stores`}
window.copyStore=id=>{const s=D.stores.find(x=>x.id===id);navigator.clipboard?.writeText(`${s.name} | ${s.address}, ${s.city}, TX | ${s.market} | ${s.deliveryDays.join(', ')}`);toast(`${s.name} copied`)};
function renderItems(){$('#itemRows').innerHTML='<tr><td colspan="9" style="padding:28px"><strong>Item-level in-stock feed not loaded yet.</strong><br><span style="color:#8b93a1">The dashboard is intentionally not showing demo in-stock percentages. Load an H-E-B item/in-stock file to activate this page.</span></td></tr>'}
function renderSales(){['#salesCases','#salesDollars','#salesItems','#salesAvg'].forEach((id,i)=>$(id).textContent=i===1?'$0':'0');$('#categoryImpact').innerHTML='<div style="color:#8b93a1;font-size:11px;padding:14px 0">Sales-added analysis will activate when item-level actions and case pricing are loaded.</div>';drawBarChart($('#salesChart'),[0,0,0,0,0],['Mon','Tue','Wed','Thu','Fri'])}
function renderSchedule(){$('#scheduleGrid').innerHTML=['Mon','Tue','Wed','Thu','Fri'].map(day=>{const b=marketBreakdown(day);return `<article class="schedule-day"><h3>${day}</h3><div class="schedule-date">${deliveryCount(day)} scheduled stores</div>${b.map(([m,c])=>`<div class="schedule-event"><strong>${m}</strong><span>${c} deliveries</span></div>`).join('')}</article>`}).join('')}
function prepCanvas(c){const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);return{x,w:r.width,h:r.height}}
function drawBarChart(c,vals,labels){if(!c)return;const {x,w,h}=prepCanvas(c),pad={l:32,r:10,t:14,b:28},max=Math.max(...vals,1),slot=(w-pad.l-pad.r)/vals.length,bw=slot*.52;x.clearRect(0,0,w,h);vals.forEach((v,i)=>{const cx=pad.l+i*slot+slot/2,bh=v/max*(h-pad.t-pad.b);x.fillStyle='#b5121b';x.fillRect(cx-bw/2,h-pad.b-bh,bw,bh);x.fillStyle='#8b93a1';x.font='10px Inter';x.fillText(labels[i],cx-11,h-8);x.fillText(String(v),cx-8,h-pad.b-bh-6)})}
function exportCSV(){const rows=[['Store','Address','City','Market','Longitude','Latitude','Mon','Tue','Wed','Thu','Fri'],...D.stores.map(s=>[s.name,s.address,s.city,s.market,s.longitude,s.latitude,...['Mon','Tue','Wed','Thu','Fri'].map(d=>s.deliveryDays.includes(d)?'X':'')])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HEB-Store-Delivery-Master.csv';a.click();URL.revokeObjectURL(a.href);toast('Store master exported')}
$('#exportBtn').onclick=exportCSV;['marketFilter','cityFilter','deliveryFilter'].forEach(id=>$(`#${id}`).onchange=renderStores);$('#globalSearch').oninput=renderStores;window.addEventListener('resize',()=>{renderOverview();if($('#salesView').classList.contains('active'))renderSales()});fillFilters();renderOverview();renderStores();renderItems();renderSales();renderSchedule();
