const D=window.HEB_DATA;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const saved=JSON.parse(localStorage.getItem('heb-item-actions')||'{}');D.items.forEach(i=>{if(saved[i.id])Object.assign(i,saved[i.id])});
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const pct=n=>`${n.toFixed(1)}%`;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function save(){const out={};D.items.forEach(i=>out[i.id]={status:i.status,qty:i.qty});localStorage.setItem('heb-item-actions',JSON.stringify(out))}
function statusFromInstock(v){return v>=97?'green':v>=93?'watch':'critical'}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active'));$$('.nav-item').forEach(b=>b.classList.remove('active'));$(`#${name}View`).classList.add('active');const nav=$(`.nav-item[data-view="${name}"]`);if(nav)nav.classList.add('active');const titles={overview:'In‑Stock Overview',stores:'Store Execution',items:'Item Tracker',sales:'Added Sales',schedule:'Field Schedule'};$('#pageTitle').textContent=titles[name];$('#sidebar').classList.remove('open');if(name==='sales')renderSales()}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
function renderOverview(){const avg=D.stores.reduce((a,b)=>a+b.instock,0)/D.stores.length;const green=D.stores.filter(s=>s.instock>=97).length;$('#heroInstock').textContent=pct(avg);$('#kpiInstock').textContent=pct(avg);$('#kpiGap').textContent=`${(98.5-avg).toFixed(1)} pts gap`;$('#kpiGreen').textContent=`${green} / ${D.stores.length}`;$('#greenPct').textContent=`${Math.round(green/D.stores.length*100)}%`;$('#sidebarGap').textContent=`Current gap: ${(98.5-avg).toFixed(1)} pts`;$('#sidebarProgress').style.width=`${Math.min(100,avg/98.5*100)}%`;
 const low=[...D.stores].sort((a,b)=>a.instock-b.instock).slice(0,5);$('#overviewStoreRows').innerHTML=low.map(s=>`<tr><td><strong>${s.name}</strong><br><span style="color:#8b93a1">${s.id}</span></td><td>${s.city}</td><td><strong>${pct(s.instock)}</strong></td><td class="${s.instock<93?'negative':''}">${(98.5-s.instock).toFixed(1)} pts</td><td><span class="pill ${statusFromInstock(s.instock)}">${statusFromInstock(s.instock).toUpperCase()}</span></td></tr>`).join('');
 $('#priorityList').innerHTML=[...D.items].sort((a,b)=>a.instock-b.instock).slice(0,5).map(i=>`<div class="priority-item"><span class="priority-dot"></span><div class="priority-main"><strong>${i.item}</strong><span>${i.store} • ${i.category}</span></div><div class="priority-score">${pct(i.instock)}</div></div>`).join('');
 $('#dowBars').innerHTML=D.dow.map(d=>`<div class="bar-row"><strong>${d.day}</strong><div class="bar-track"><div class="bar-fill" style="width:${d.v}%"></div></div><strong>${pct(d.v)}</strong></div>`).join('');drawLineChart($('#trendChart'),D.trend,D.days,98.5)}
function fillFilters(){[...new Set(D.stores.map(s=>s.city))].sort().forEach(c=>$('#cityFilter').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));[...new Set(D.items.map(i=>i.category))].sort().forEach(c=>$('#categoryFilter').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`))}
function renderStores(){const stat=$('#storeStatusFilter').value,city=$('#cityFilter').value,q=$('#globalSearch').value.toLowerCase();const arr=D.stores.filter(s=>(stat==='all'||statusFromInstock(s.instock)===stat)&&(city==='all'||s.city===city)&&(!q||`${s.name} ${s.city} ${s.id}`.toLowerCase().includes(q)));$('#storeRows').innerHTML=arr.map(s=>`<tr><td><strong>${s.name}</strong><br><span style="color:#8b93a1">${s.id}</span></td><td>${s.city}</td><td><strong>${pct(s.instock)}</strong></td><td class="${s.delta>=0?'positive':'negative'}">${s.delta>=0?'+':''}${s.delta.toFixed(1)} pts</td><td>${s.oos}</td><td>${s.delivery}</td><td><span class="pill ${statusFromInstock(s.instock)}">${statusFromInstock(s.instock).toUpperCase()}</span></td><td><button class="text-btn" onclick="jumpToStoreItems('${s.name.replaceAll("'","\\'")}')">Work items →</button></td></tr>`).join('')||'<tr><td colspan="8">No stores match the current filters.</td></tr>'}
window.jumpToStoreItems=name=>{setView('items');$('#globalSearch').value=name;renderItems()};
function renderItems(){const cat=$('#categoryFilter').value,stat=$('#itemStatusFilter').value,q=$('#globalSearch').value.toLowerCase();const arr=D.items.filter(i=>(cat==='all'||i.category===cat)&&(stat==='all'||i.status===stat)&&(!q||`${i.item} ${i.store} ${i.category}`.toLowerCase().includes(q)));$('#itemRows').innerHTML=arr.map(i=>`<tr><td><span class="pill ${i.priority==='High'?'critical':i.priority==='Medium'?'watch':'green'}">${i.priority}</span></td><td><strong>${i.item}</strong></td><td>${i.category}</td><td>${i.store}</td><td><strong>${pct(i.instock)}</strong></td><td><select onchange="updateStatus(${i.id},this.value)"><option ${i.status==='Open'?'selected':''}>Open</option><option ${i.status==='Added'?'selected':''}>Added</option><option ${i.status==='Verified'?'selected':''}>Verified</option></select></td><td><select class="qty-select" onchange="updateQty(${i.id},this.value)">${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${i.qty===n?'selected':''}>${n}</option>`).join('')}</select></td><td>${money(i.casePrice)}</td><td class="money">${money(i.qty*i.casePrice)}</td></tr>`).join('')||'<tr><td colspan="9">No items match the current filters.</td></tr>';renderImpactKpis()}
window.updateStatus=(id,v)=>{const i=D.items.find(x=>x.id===id);i.status=v;save();toast(`Status updated: ${v}`)};window.updateQty=(id,v)=>{const i=D.items.find(x=>x.id===id);i.qty=Number(v);if(i.qty>0&&i.status==='Open')i.status='Added';save();renderItems();toast(`${i.qty} case${i.qty===1?'':'s'} added • ${money(i.qty*i.casePrice)}`)};
function impact(){const actioned=D.items.filter(i=>i.qty>0);const cases=actioned.reduce((a,b)=>a+b.qty,0);const dollars=actioned.reduce((a,b)=>a+b.qty*b.casePrice,0);return{actioned,cases,dollars}}
function renderImpactKpis(){const x=impact();$('#kpiCases').textContent=x.cases;$('#kpiDollars').textContent=money(x.dollars);$('#caseTrend').textContent=x.cases?'Captured this session':'Ready to track';$('#dollarTrend').textContent=x.dollars?`${x.actioned.length} items actioned`:'Live'}
function renderSales(){const x=impact();$('#salesCases').textContent=x.cases;$('#salesDollars').textContent=money(x.dollars);$('#salesItems').textContent=x.actioned.length;$('#salesAvg').textContent=money(x.actioned.length?x.dollars/x.actioned.length:0);const byCat={};x.actioned.forEach(i=>byCat[i.category]=(byCat[i.category]||0)+i.qty*i.casePrice);const rows=Object.entries(byCat).sort((a,b)=>b[1]-a[1]);$('#categoryImpact').innerHTML=rows.length?rows.map(([c,v])=>`<div class="impact-item"><div class="impact-top"><span>${c}</span><strong>${money(v)}</strong></div><div class="impact-bar"><div style="width:${x.dollars?v/x.dollars*100:0}%"></div></div></div>`).join(''):'<div style="color:#8b93a1;font-size:11px;padding:14px 0">Add cases in Item Tracker to populate this analysis.</div>';const vals=[0,0,0,0,0,0,x.dollars];drawBarChart($('#salesChart'),vals,['Thu','Fri','Sat','Sun','Mon','Tue','Wed'])}
function renderSchedule(){$('#scheduleGrid').innerHTML=D.schedule.map(d=>`<article class="schedule-day"><h3>${d.day}</h3><div class="schedule-date">${d.date}</div>${d.events.map(e=>`<div class="schedule-event"><strong>${e[0]}</strong><span>${e[1]}</span></div>`).join('')}</article>`).join('')}
function prepCanvas(c){const r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);return{x,w:r.width,h:r.height}}
function drawLineChart(c,vals,labels,goal){if(!c)return;const {x,w,h}=prepCanvas(c),pad={l:35,r:12,t:12,b:28},min=88,max=100,xx=i=>pad.l+i*(w-pad.l-pad.r)/(vals.length-1),yy=v=>pad.t+(max-v)*(h-pad.t-pad.b)/(max-min);x.clearRect(0,0,w,h);x.font='10px Inter';x.fillStyle='#8b93a1';x.strokeStyle='#e8ebef';[90,94,98].forEach(v=>{x.beginPath();x.moveTo(pad.l,yy(v));x.lineTo(w-pad.r,yy(v));x.stroke();x.fillText(`${v}%`,2,yy(v)+3)});x.setLineDash([5,5]);x.strokeStyle='#9ca3af';x.beginPath();x.moveTo(pad.l,yy(goal));x.lineTo(w-pad.r,yy(goal));x.stroke();x.setLineDash([]);x.strokeStyle='#b5121b';x.lineWidth=3;x.beginPath();vals.forEach((v,i)=>i?x.lineTo(xx(i),yy(v)):x.moveTo(xx(i),yy(v)));x.stroke();vals.forEach((v,i)=>{x.fillStyle='#b5121b';x.beginPath();x.arc(xx(i),yy(v),3.5,0,Math.PI*2);x.fill();x.fillStyle='#8b93a1';x.fillText(labels[i],xx(i)-10,h-8)});x.lineWidth=1}
function drawBarChart(c,vals,labels){if(!c)return;const {x,w,h}=prepCanvas(c),pad={l:30,r:10,t:12,b:28},max=Math.max(...vals,100),bw=(w-pad.l-pad.r)/vals.length*.58;x.clearRect(0,0,w,h);vals.forEach((v,i)=>{const slot=(w-pad.l-pad.r)/vals.length,cx=pad.l+i*slot+slot/2,bh=v/max*(h-pad.t-pad.b);x.fillStyle='#b5121b';x.fillRect(cx-bw/2,h-pad.b-bh,bw,bh);x.fillStyle='#8b93a1';x.font='10px Inter';x.fillText(labels[i],cx-10,h-8)})}
function exportCSV(){const rows=[['Priority','Item','Category','Store','In-Stock','Status','Qty Added','Case Price','Sales Added'],...D.items.map(i=>[i.priority,i.item,i.category,i.store,i.instock,i.status,i.qty,i.casePrice,(i.qty*i.casePrice).toFixed(2)])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='HEB-InStock-Command-Center.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV exported')}
$('#exportBtn').onclick=exportCSV;['storeStatusFilter','cityFilter'].forEach(id=>$(`#${id}`).onchange=renderStores);['categoryFilter','itemStatusFilter'].forEach(id=>$(`#${id}`).onchange=renderItems);$('#globalSearch').oninput=()=>{renderStores();renderItems()};window.addEventListener('resize',()=>{renderOverview();if($('#salesView').classList.contains('active'))renderSales()});fillFilters();renderOverview();renderStores();renderItems();renderSchedule();